name: Build and Deploy

on:
  push:
    branches: [ main ]

# Add permissions for GitHub Actions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Touch .nojekyll file to skip Jekyll on GitHub Pages
        run: |
          mkdir -p static
          touch static/.nojekyll

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }} 