name: Blog update build and deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'content/pull_request/**'
      - 'content/posts/**'
      - 'content/_index.md'
      - 'content/about.md'
      - 'templates/**'
      - 'sass/**'
      - 'static/js/**'
      - 'static/scss/**'
      - 'config.toml'
  
  # Manual trigger for blog updates
  workflow_dispatch:

# Add permissions for GitHub Actions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Restore WASM projects from gh-pages
        run: |
          echo "Restoring WASM projects from gh-pages branch..."
          
          # Try to get WASM files from existing gh-pages branch
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            echo "Found existing gh-pages branch, restoring WASM projects..."
            
            # Create temporary directory for gh-pages content
            mkdir -p temp-gh-pages
            git worktree add temp-gh-pages origin/gh-pages
            
            # Restore WASM project files from gh-pages
            if [ -d "temp-gh-pages/content/projects" ]; then
              echo "Restoring content/projects..."
              mkdir -p content/projects
              cp -r temp-gh-pages/content/projects/* content/projects/ 2>/dev/null || true
              echo "Restored WASM projects:"
              find content/projects -name "*.wasm" -o -name "*.js" | head -10
            fi
            
            if [ -d "temp-gh-pages/static/assets" ]; then
              echo "Restoring static/assets..."
              mkdir -p static/assets
              cp -r temp-gh-pages/static/assets/* static/assets/ 2>/dev/null || true
            fi
            
            # Clean up
            git worktree remove temp-gh-pages
            echo "WASM projects restored"
          else
            echo "No existing gh-pages branch found"
            mkdir -p content/projects static/assets
          fi

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }} 